### ISSUE TITLE
run “python train_segmentor.py" show ValueError: Input contains NaN.,how to solve thie issue?

### ISSUE THREAD

**Issue by quweijun** [Tokichan/CSAD#3]
Current loss: 1.5696| CE:0.2391| Dice:0.4271| Hist:1.6467| Focal:0.9034| Entropy:0.2268(0.227
Traceback (most recent call last):
  File "/home/ubuntu/CSAD-main/train_segmentor.py", line 148, in <module>
    segmentor.fit(sup_dataloader,unsup_dataloader,val_dataloader,test_dataloader,full_train_dataloader)
  File "/home/ubuntu/CSAD-main/models/segmentation/segmentor.py", line 99, in fit
    logi_auc, struc_auc = test_patch_histogram(
  File "/home/ubuntu/CSAD-main/models/segmentation/patch_histogram.py", line 170, in test_patch_histogram
    logi_auc = roc_auc_score(logi_true_score, logi_score)*100
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 619, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

**Comment by Tokichan** [comment]
Try using Euclidean distance instead of Mahalanobis distance in the patch_histogram.py (you can use similar codes from models/onnx_model.py line 87~92)
